Get http://localhost:3000/users
### 

Post http://localhost:3000/users/test 
Content-Type: application/json


### payment request
Post http://localhost:3000/users/payment 
Content-Type: application/json

{"tokenId": "pk_test_51Q0OsODmVJRVlYWkkRMV6XZ4NcD9VOVBEdsCb0ypBuBtQN4NL7bDDZFJETo7JwD7XA2uYNbTVqkk3A3Z115I1zaY00RVrJ1opv", "amount": 2000}


### payment intent

Post http://localhost:3000/users/intent 
Content-Type: application/json

{"currency": "usd", "amount": 2000}

### new user **** unquote route to change password

Post http://localhost:3000/users/signup 
Content-Type: application/json

{"firstName": "Craig", "lastName":"Mar", "userName":"cmar@yahoo.com", "password": "123456", "confirm": "123456"}

### login get token *** put in proper password

Post http://localhost:3000/users/login 
Content-Type: application/json

{ "email":"cmar@yahoo.com", "password": "123456" }

### new product

Post http://localhost:3000/products/new 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzMzODU3MDMxLCJleHAiOjE3MzM4NTkwMzF9.qri07G-oEboSnN_6SkmSzc4UTcD9iApKRFNxxOVFP1w
Content-Type: application/json

{"title":"edit test", "text":"edit Lorem ipsum dolor sit " }


### multipart form request with webkit
POST http://localhost:3000/products/new HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzMzODU5MTY1LCJleHAiOjE3MzM4NjExNjV9.7U5T2RMLIiy5z_XYyrCVqiuawY8Ivp7e-JujkTi2Q6g
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="brand"

simano
--MfnBoundry
Content-Disposition: form-data; name="color"

siver
--MfnBoundry
Content-Disposition: form-data; name="description"

mtb bike chain
--MfnBoundry
Content-Disposition: form-data; name="modelNum"

10273s 
--MfnBoundry
Content-Disposition: form-data; name="price"

100
--MfnBoundry
Content-Disposition: form-data; name="quantity"

10
--MfnBoundry
Content-Disposition: form-data; name="title"

bike chain
--MfnBoundry
Content-Disposition: form-data; name="category"

bike
--MfnBoundry
Content-Disposition: form-data; name="length"

10
--MfnBoundry
Content-Disposition: form-data; name="width"

5
--MfnBoundry
Content-Disposition: form-data; name="height"

1
--MfnBoundry
Content-Disposition: form-data; name="weight"

2
--MfnBoundry
Content-Disposition: form-data; name="image"; filename="./me.JPG" 
Content-Type: image/jpeg

< ./me.JPG 
--MfnBoundry--

### get all products

GET http://localhost:3000/users/all 

 

### delete product

Delete http://localhost:3000/products/delete/66f70af1d5bff40e80b37cfd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzI3NDY3MjIxLCJleHAiOjE3Mjc0NjkyMjF9.CJVbDEFPpFikN5F30c9bgF6ynN2UsWBlrW9aBPCj10M

### publish product

PUT http://localhost:3000/products/publish/66f61663764140d30b4d1a0b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzI3NDY3MjIxLCJleHAiOjE3Mjc0NjkyMjF9.CJVbDEFPpFikN5F30c9bgF6ynN2UsWBlrW9aBPCj10M
Content-Type: application/json


### delete pic

Delete http://localhost:3000/products/image/66f71e4c586e6e1d9a3774ef
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzI3NDcxMDQ3LCJleHAiOjE3Mjc0NzMwNDd9.7MM4QQy7nwdfMbj-hXNGVTzzja3ZfRrrbHITFd4CXJk


### add pic to product
POST http://localhost:3000/products/image/66f71e4c586e6e1d9a3774ef HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzMzODU0OTM0LCJleHAiOjE3MzM4NTY5MzR9.OCmCoKlNNnPewFK9DIJYvJxwILtmHQwgfWjp0ffWSa4
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="image"; filename="./me.JPG" 
Content-Type: image/jpeg

< ./me.JPG 
--MfnBoundry--

### resize pic
POST http://localhost:3000/products/resize HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzMzODU0OTM0LCJleHAiOjE3MzM4NTY5MzR9.OCmCoKlNNnPewFK9DIJYvJxwILtmHQwgfWjp0ffWSa4
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="image"; filename="./me.JPG" 
Content-Type: image/jpeg

< ./me.JPG 
--MfnBoundry--

### edit post

PUT http://localhost:3000/products/edit/66f82948b219f89bc7421dcc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzI3NTQwODgyLCJleHAiOjE3Mjc1NDI4ODJ9.BXGVTlie1YZJI0g6KpErNAK4ZC7d2oS5282ehKOomqs
Content-Type: application/json

{
      "title": "productData.title",
      "category": "productData.category",
      "brand": "productData.brand",
      "color": "productData.color",
      "description": "productData.description",
      "modelNum": "productData.modelNum",
      "price": "productData.price",
      "length": "productData.length",
      "width": "productData.width",
      "height": "productData.height",
      "weight": "productData.weight",
      "quantity": "productData.quantity"
      
    

    }

### edit post

PUT http://localhost:3000/products/edit/66f82948b219f89bc7421dcc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzI3NTM4NzM3LCJleHAiOjE3Mjc1NDA3Mzd9.Yl919elSS7esKRgPfg0deKaaTU9TC5gfNMVIk64BUNU
Content-Type: application/json

{
     

    }

### usps get shipping price

Post http://localhost:3000/users/usps
Content-Type: application/json

{
      "originZIPCode": "22407",
        "destinationZIPCode": "63118",
        "weight": 20.25,
        "length": 14.5,
        "width": 12.5,
        "height": 24,
        "mailClass": "USPS_GROUND_ADVANTAGE",
        "processingCategory": "NON_MACHINABLE",
        "rateIndicator": "SP",
        "destinationEntryFacilityType": "NONE",
        "priceType": "COMMERCIAL"
    

    }


### new order
    
Post http://localhost:3000/users/newOrder 
Content-Type: application/json

{
      "orderId": "12edf",
      "firstName": "Craig",
        "lastName": "Mar",
        "address1": "10 a st",
        "address2": "apt 2",
        "email": "c@yahhoo.com",
        "town": "red bank",
        "state": "nj",
        "zip": "07701",
        "shippingCost": 12.00,
        "orderCost": 25.00,
        "productsArray": [{
        "id": "4a482549-79aa-4798-8a3b-a19746cd645a",
        "title": "Microsoft Xbox X/S Wireless Controller Robot White",
        "price": 57,
        "quantity": 1,
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692255251854-xbox.jpg"
    },
    {
        "id": "827ab3f1-b5d5-436a-93cc-7a4a28aefd3b",
        "title": "Sony WH-1000XM3 Bluetooth Wireless Over Ear Headphones with Mic (Silver)",
        "price": 773,
        "quantity": 2,
        "total": 1546.00,
        "image": "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692947383286-714WUJlhbLS._SL1500_.jpg"
    }
    
]

    }

### change shipping status

PUT http://localhost:3000/products/shipped/673bd72d4ba82eb8d0a436dc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzMyMTI4Nzg4LCJleHAiOjE3MzIxMzA3ODh9.FTUOgXFiWywz0MgD3_nt509ZyximrwnUrIZZ24ExkOs
Content-Type: application/json

### get all orders

GET http://localhost:3000/products/orders 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzMyMTMzMjkwLCJleHAiOjE3MzIxMzUyOTB9.E3XCfxKxTvGEyMoI7twwihP6yXR3SCysk28SSgFsOng
 

### delete order

Delete http://localhost:3000/products/deleteOrder/673e419cff72c7054a666add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzMyMjEyNzkxLCJleHAiOjE3MzIyMTQ3OTF9.guxYVDx-KTwnS2k0TQpE3YnTOgznk_gQALspGi8Gkfw

### send email

Post http://localhost:3000/users/email 
Content-Type: application/json

{
      "order_details": "Order details new",
       "email": "cmarcinkiewicz2000@yahoo.com"

    }

### new category
POST http://localhost:3000/products/new_category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzM1NjAwOTA4LCJleHAiOjE3MzU2MDI5MDh9.uFENERp4h7mqHV-RHSrfKUY_-4FpeYKwQxk-MUhy100
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="name"

camp

--MfnBoundry
Content-Disposition: form-data; name="image"; filename="./me.JPG" 
Content-Type: image/jpeg

< ./me.JPG 
--MfnBoundry--

### get all published

Get http://localhost:3000/users/published