Get http://localhost:3000/users
### 

Post http://localhost:3000/users/test 
Content-Type: application/json


### payment request
Post http://localhost:3000/users/payment 
Content-Type: application/json

{"tokenId": "pk_test_51Q0OsODmVJRVlYWkkRMV6XZ4NcD9VOVBEdsCb0ypBuBtQN4NL7bDDZFJETo7JwD7XA2uYNbTVqkk3A3Z115I1zaY00RVrJ1opv", "amount": 2000}


### payment intent

Post http://localhost:3000/users/intent 
Content-Type: application/json

{"currency": "usd", "amount": 2000}

### new user

Post http://localhost:3000/users/signup 
Content-Type: application/json

{"firstName": "Craig", "lastName":"Mar", "userName":"cmar@yahoo.com", "password": "123456", "confirm": "123456"}

### login get token

Post http://localhost:3000/users/login 
Content-Type: application/json

{ "userName":"cmar@yahoo.com", "password": "123456" }

### new product

Post http://localhost:3000/products/new 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzI3Mzg3OTUxLCJleHAiOjE3MjczODk5NTF9.HdnvkPt3KvVn-c1wu2mopupOSJZfvtuKPYkeVIBh8TI
Content-Type: application/json

{"title":"edit test", "text":"edit Lorem ipsum dolor sit " }


### multipart form request with webkit
POST http://localhost:3000/products/new HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzI3NDY2MTkyLCJleHAiOjE3Mjc0NjgxOTJ9.vHbaqqKo8Nvmg9-bYUqej1FWJSNTq0-0FLZdCHX2LSQ
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="brand"

brand
--MfnBoundry
Content-Disposition: form-data; name="color"

color
--MfnBoundry
Content-Disposition: form-data; name="description"

description
--MfnBoundry
Content-Disposition: form-data; name="modelNum"

model number 
--MfnBoundry
Content-Disposition: form-data; name="price"

100
--MfnBoundry
Content-Disposition: form-data; name="quantity"

10
--MfnBoundry
Content-Disposition: form-data; name="title"

title
--MfnBoundry
Content-Disposition: form-data; name="category"

category
--MfnBoundry
Content-Disposition: form-data; name="length"

10
--MfnBoundry
Content-Disposition: form-data; name="width"

5
--MfnBoundry
Content-Disposition: form-data; name="height"

1
--MfnBoundry
Content-Disposition: form-data; name="weight"

2
--MfnBoundry
Content-Disposition: form-data; name="image"; filename="./me.JPG" 
Content-Type: image/jpeg

< ./me.JPG 
--MfnBoundry--

### get all products

GET http://localhost:3000/products/all 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzI3NDY3MjIxLCJleHAiOjE3Mjc0NjkyMjF9.CJVbDEFPpFikN5F30c9bgF6ynN2UsWBlrW9aBPCj10M

### delete product

Delete http://localhost:3000/products/delete/66f70af1d5bff40e80b37cfd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImNtYXJAeWFob28uY29tIiwiaWF0IjoxNzI3NDY3MjIxLCJleHAiOjE3Mjc0NjkyMjF9.CJVbDEFPpFikN5F30c9bgF6ynN2UsWBlrW9aBPCj10M